# Mark this as true if there is a custom server to set the "join" button to redirect to your server
enabledServerCheck = false

# Your server address
serverAddress = "ponchisaohosting.xyz"

# Your server port
serverPort = 25565