# JDBR URL connection
jdbc = "jdbc:mysql://BDIP:3306/your_database"

# DataBase user
user = "your_user"

# DataBase password
password = "your_password"

# Initial day (integer)
day = 1

# DeathTrain status
deathTrain = false
