# URL de conexión JDBC
jdbc = "jdbc:mysql://BDIP:3306/your_database"

# Usuario de la base de datos
user = "your_user"

# Contraseña de la base de datos
password = "your_password"

# Día inicial (entero)
day = 1

# Activar tren de la muerte
deathTrain = false
